--
-- PostgreSQL database dump
--

\restrict 31yttrrrt84JvdvBtAAczgIST4HNmWevi6Ehe7uMfr3P03gPZGQvbD9eM0tLzwz

-- Dumped from database version 15.14 (Debian 15.14-1.pgdg13+1)
-- Dumped by pg_dump version 15.14 (Debian 15.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE ONLY public.user_profile DROP CONSTRAINT fkuganfwvnbll4kn2a3jeyxtyi;
DROP INDEX public.flyway_schema_history_s_idx;
ALTER TABLE ONLY public.users DROP CONSTRAINT users_pkey;
ALTER TABLE ONLY public.user_profile DROP CONSTRAINT user_profile_pkey;
ALTER TABLE ONLY public.users DROP CONSTRAINT ukr43af9ap4edm43mmtq01oddj6;
ALTER TABLE ONLY public.user_profile DROP CONSTRAINT ukebc21hy5j7scdvcjt0jy6xxrv;
ALTER TABLE ONLY public.users DROP CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7;
ALTER TABLE ONLY public.jwtblack_listed_tokens DROP CONSTRAINT jwtblack_listed_tokens_pkey;
ALTER TABLE ONLY public.flyway_schema_history DROP CONSTRAINT flyway_schema_history_pk;
DROP SEQUENCE public.users_seq;
DROP TABLE public.users;
DROP TABLE public.user_profile;
DROP TABLE public.jwtblack_listed_tokens;
DROP TABLE public.flyway_schema_history;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


ALTER TABLE public.flyway_schema_history OWNER TO postgres;

--
-- Name: jwtblack_listed_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jwtblack_listed_tokens (
    token character varying(255) NOT NULL,
    expiration_date timestamp(6) with time zone
);


ALTER TABLE public.jwtblack_listed_tokens OWNER TO postgres;

--
-- Name: user_profile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_profile (
    profile_id bigint NOT NULL,
    first_name character varying(255),
    height double precision,
    last_name character varying(255),
    profile_picture_name character varying(255),
    profile_picture_src character varying(255),
    weight double precision,
    user_id bigint
);


ALTER TABLE public.user_profile OWNER TO postgres;

--
-- Name: user_profile_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_profile ALTER COLUMN profile_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_profile_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255),
    role character varying(255),
    username character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.users_seq OWNER TO postgres;

--
-- Data for Name: flyway_schema_history; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.flyway_schema_history (installed_rank, version, description, type, script, checksum, installed_by, installed_on, execution_time, success) FROM stdin;
\.


--
-- Data for Name: jwtblack_listed_tokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.jwtblack_listed_tokens (token, expiration_date) FROM stdin;
eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJCZW5jZSIsImlhdCI6MTc2MzEyMzMyNywiZXhwIjoxNzYzMTI1MTI3fQ.Rtj8P-SZqAzqjPuH8iLceSCjSUNWv5HUn8oT4SKJiCo	2025-11-14 12:58:47+00
eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJCZW5jZSIsImlhdCI6MTc2NTIwODkxOSwiZXhwIjoxNzY1MjEwNzE5fQ._3HRGXgaoOUMaNvZAqTCEMtPzLCACmrroeSpW0T9R9A	2025-12-08 16:18:39+00
eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJCZW5jZSIsImlhdCI6MTc2NTIwODk5NCwiZXhwIjoxNzY1MjEwNzk0fQ.pKTlGcyEnLb9a8BbbuV8HPwdHD7SYjM5_yTQLwazQvo	2025-12-08 16:19:54+00
eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJCZW5jZSIsImlhdCI6MTc2NTIwOTA0OSwiZXhwIjoxNzY1MjEwODQ5fQ.NhYz8Y1m6RgErXcXspPvyNDluHZb3kNOfaYn9bB6EJI	2025-12-08 16:20:49+00
eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJCZW5jZSIsImlhdCI6MTc2NTIxNDQ3MiwiZXhwIjoxNzY1MjE2MjcyfQ.60xK4JHh7nlNa52yxAWyoY_ay-h4hC9ibIVfmJJDXLs	2025-12-08 17:51:12+00
eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJGaXR6IiwiaWF0IjoxNzY1NDkzMTQxLCJleHAiOjE3NjU0OTQ5NDF9.P3kTPh1zxHaZXhg0_jjk9E7rVUx_NGQptGTyCiCLWt8	2025-12-11 23:15:41+00
eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJGaXR6IiwiaWF0IjoxNzY1NTQ4OTM5LCJleHAiOjE3NjU1NTA3Mzl9.rObPNcGS0SCEeurkpt3iiTCl325fnGHdkenM8C54Jck	2025-12-12 14:45:39+00
eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJCZW5jZSIsImlhdCI6MTc2NTU2MDc4MiwiZXhwIjoxNzY1NTYyNTgyfQ.yZks0_2e76x00YU2jLDI4YGJYAXjqvbc_NExioEV46s	2025-12-12 18:03:02+00
eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJGaXR6IiwiaWF0IjoxNzY1NTYwNzkzLCJleHAiOjE3NjU1NjI1OTN9.LOhIeATzXiVyb9fEtPNdKsMzUyQ-RbCD4X2CCP_h1eA	2025-12-12 18:03:13+00
eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJCZW5jZSIsImlhdCI6MTc2NTU3MDc4NiwiZXhwIjoxNzY1NTcyNTg2fQ.GeuBWd_rrp3y_7EcYteHBPrKUe8orNc01A0ZUhuzPwo	2025-12-12 20:49:46+00
eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJGaXR6IiwiaWF0IjoxNzY1ODAxNjE1LCJleHAiOjE3NjU4MDM0MTV9.k8_v_fQ3t8QbPFgrqqlxK8u3qWzC6IMuOvTZhRrPlHI	2025-12-15 12:56:55+00
\.


--
-- Data for Name: user_profile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_profile (profile_id, first_name, height, last_name, profile_picture_name, profile_picture_src, weight, user_id) FROM stdin;
1	FitzChivalry	180	Farseer	Screenshot_1.png	https://fitness-tracker-project.s3.eu-north-1.amazonaws.com/Screenshot_1.png	75	704
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, email, password, role, username) FROM stdin;
202	testuser@gmail.com	$2a$10$Tm4SsqKmOtYczPOhwBWZteyEBhYCnnc5uQ77ynyrkrd5MC6b/8KES	USER	TestUser
302	verity@gmail.com	$2a$10$ggFnpUoEnSnwHLCuTmnCmeHPM1sKyx78aSy0FMkt/nn84OoSc8YFW	USER	Verity
602	vesabence@gmail.com	$2a$10$tRj6/EL915GJBr4DbtH38edB/B2ygnx7hbV.NA0vK//Kr/Yru309C	ADMIN	Bence
704	spiderbence1100@gmail.com	$2a$10$LCfmw/r4MGfQN/zeJ/MM9eY3Fl0ccWm/.7sFKHOSh0HSnON3Z46mC	USER	Fitz
\.


--
-- Name: user_profile_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_profile_profile_id_seq', 1, true);


--
-- Name: users_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_seq', 751, true);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: jwtblack_listed_tokens jwtblack_listed_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jwtblack_listed_tokens
    ADD CONSTRAINT jwtblack_listed_tokens_pkey PRIMARY KEY (token);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: user_profile ukebc21hy5j7scdvcjt0jy6xxrv; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT ukebc21hy5j7scdvcjt0jy6xxrv UNIQUE (user_id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: user_profile user_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT user_profile_pkey PRIMARY KEY (profile_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: user_profile fkuganfwvnbll4kn2a3jeyxtyi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT fkuganfwvnbll4kn2a3jeyxtyi FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 31yttrrrt84JvdvBtAAczgIST4HNmWevi6Ehe7uMfr3P03gPZGQvbD9eM0tLzwz

